source .venv/bin/activate
PYTHONPATH=. python -u main.py +name=test_inpaint_rl \
    dataset=custom_scene \
    dataset.processed_scene_data_path=data/metadatas/custom_scene_metadata.json \
    dataset.max_num_objects_per_scene=12 \
    algorithm=scene_diffuser_midiffusion\
    algorithm.classifier_free_guidance.use=False \
    algorithm.ema.use=False \
    algorithm.trainer=rl_score \
    algorithm.noise_schedule.scheduler=ddim \
    algorithm.noise_schedule.ddim.num_inference_timesteps=150 \
    experiment.training.max_steps=2e6 \
    experiment.validation.limit_batch=1 \
    experiment.validation.val_every_n_step=50 \
    algorithm.ddpo.ddpm_reg_weight=50.0 \
    experiment.reset_lr_scheduler=True \
    experiment.training.lr=1e-6 \
    experiment.lr_scheduler.num_warmup_steps=250 \
    algorithm.ddpo.batch_size=4 \
    experiment.training.checkpointing.every_n_train_steps=500 \
    algorithm.num_additional_tokens_for_sampling=0 \
    algorithm.ddpo.n_timesteps_to_sample=100 \
    experiment.find_unused_parameters=True \
    algorithm.custom.loss=true \
    algorithm.validation.num_samples_to_render=0 \
    algorithm.validation.num_samples_to_visualize=0 \
    algorithm.validation.num_directives_to_generate=0 \
    algorithm.test.num_samples_to_render=0 \
    algorithm.test.num_samples_to_visualize=0 \
    algorithm.test.num_directives_to_generate=0 \
    algorithm.validation.num_samples_to_compute_physical_feasibility_metrics_for=0 \
    experiment.training.precision=bf16-mixed \
    algorithm.ddpo.use_universal_reward=True \
    algorithm.ddpo.universal_reward.use_physcene_reward=True \
    algorithm.classifier_free_guidance.use_floor=True \
    load=rrudae6n \
    algorithm.classifier_free_guidance.weight=1.0 \
    algorithm.custom.old=True \
    algorithm.predict.inpaint_masks='{ceiling_lamp: 4}' \
    algorithm.ddpo.use_inpaint=True \

# PYTHONPATH=. python -u main.py +name=continuous_mi_bedroom_floor_obj32 \
#     dataset=custom_scene \
#     dataset.data.dataset_directory=bedroom \
#     dataset.data.path_to_processed_data=/media/ajad/YourBook/AshokSaugatResearchBackup/AshokSaugatResearch/3d_front_data \
#     dataset.processed_scene_data_path=data/metadatas/custom_scene_metadata.json \
#     dataset._name=custom_scene \
#     dataset.max_num_objects_per_scene=12 \
#     algorithm=scene_diffuser_midiffusion \
#     algorithm.trainer=ddpm \
#     algorithm.custom.objfeat_dim=32 \
#     experiment.find_unused_parameters=True \
#     algorithm.classifier_free_guidance.use=False \
#     algorithm.classifier_free_guidance.use_floor=True \
#     algorithm.classifier_free_guidance.weight=0 \
#     algorithm.custom.obj_vec_len=62 \
#     algorithm.custom.obj_diff_vec_len=62 \
#     algorithm.custom.loss=true \
#     algorithm.validation.num_samples_to_render=0 \
#     algorithm.validation.num_samples_to_visualize=0 \
#     algorithm.validation.num_directives_to_generate=0 \
#     algorithm.test.num_samples_to_render=0 \
#     algorithm.test.num_samples_to_visualize=0 \
#     algorithm.test.num_directives_to_generate=0 \
#     algorithm.validation.num_samples_to_compute_physical_feasibility_metrics_for=0 \
#     dataset.data.encoding_type=cached_diffusion_cosin_angle_objfeats_lat32_wocm
